<?php

/**
 * @file
 * Functions to support theming in the Stagup Classy theme.
 */
 
 /**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function stagupclassy_preprocess_block(&$variables) {
  $variables['basepath'] = base_path();
  $logopath = '/' . 
              drupal_get_path('theme','stagupclassy') . 
              '/FairfieldStagUp.png';
  if (base_path() != "/") 
    $logopath = base_path() . $logopath;
  $variables['logopath'] = $logopath ;
}